owner: cerberauth
repo: upptime

sites:
  - name: Status Page
    url: https://status.cerberauth.com
    maxResponseTime: 1000

assignees:
  - emmanuelgautier

status-website:
  cname: status.cerberauth.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CerberAuth Old Status
  introTitle: "CerberAuth Old Status"
  introMessage: "Old Monitor CerberAuth's services uptime and status"
  navbar:
    - title: Status Page
      href: https://status.cerberauth.com
    - title: GitHub
      href: https://github.com/$OWNER
